{% set name = "Protego" %}
{% set version = "0.6.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 3466f41438421cf90008e98534d5fde47dc16a17482571d021143ac18b70ace9

build:
  number: 0
  script: 
    # limiting test data to robots.txt files with names that don't raise eyebrows
    - mv tests/test_data tests/test_data_bak   # [unix]
    - move tests/test_data tests/test_data_bak # [win]
    - mkdir tests/test_data
    - mv tests/test_data_bak/ca.yahoo.com tests/test_data/test.com   # [unix]
    - move tests/test_data_bak/ca.yahoo.com tests/test_data/test.com # [win]
    - rm -rf tests/test_data_bak         # [unix]
    - rmdir /s /q tests/test_data_bak    # [win]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling >=1.27.0
  run:
    - python

test:
  imports:
    - protego
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/scrapy/protego
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A pure-Python robots.txt parser with support for modern conventions
  description: |
    A pure-Python robots.txt parser with support for modern conventions
    like the one defined by Google.
  doc_url: https://github.com/scrapy/protego
  dev_url: https://github.com/scrapy/protego


extra:
  recipe-maintainers:
    - Gallaecio
